---
- name: "Install isc dhcpd"
  pkgng:
    name: "isc-dhcp44-server"
    state: "present"

- name: "Enable isc dhcpd in rc.conf"
  sysrc:
    name: "dhcpd_enable"
    value: "YES"

- name: "set dhcpd_ifaces in /etc/rc.conf"
  sysrc:
    name: "dhcpd_ifaces"
    value: "{{ isc_dhcpd_interfaces|join(',') }}"
  when: isc_dhcpd_interfaces

- name: "set dhcpd6_ifaces in /etc/rc.conf"
  sysrc:
    name: "dhcpd6_ifaces"
    value: "{{ isc_dhcpd6_interfaces|join(',') }}"
  when:
    - isc_dhcpd6
    - dhcpd6_interfaces

- name: "Copy dhcpd.conf"
  template:
    src: "dhcpd.conf.j2"
    dest: "/usr/local/etc/dhcpd.conf"
  tags:
    - "dhcpd"
  notify: "restart isc dhcpd"

- name: "Enable isc dhcpd6 in rc.conf"
  sysrc:
    name: "dhcpd6_enable"
    value: "YES"
  when: isc_dhcpd6|default(False)

- name: "Copy dhcpd6.conf"
  template:
    src: "dhcpd6.conf.j2"
    dest: "/usr/local/etc/dhcpd6.conf"
  tags:
    - "dhcpd"
  notify: "restart isc dhcpd6"
