---
- name: "Get source code for uwsgi_exporter"
  git:
    repo: "https://github.com/timonwong/uwsgi_exporter"
    dest: "/root/uwsgi_exporter"
    force: yes
    version: "{{ uwsgi_exporter_version }}"
  register: gitresult

- name: "Install Go to build uwsgi_exporter"
  pkgng:
    name: "go"
    state: "present"
  register: goresult
  when: gitresult.changed

- name: "Install gmake to build uwsgi_exporter"
  pkgng:
    name: "gmake"
    state: "present"
  register: gmakeresult
  when: gitresult.changed

- name: "build uwsgi_exporter"
  command: "gmake"
  args:
    chdir: "/root/uwsgi_exporter"
  when: gitresult.changed

- name: "Copy uwsgi_exporter binary to /usr/local/bin"
  copy:
   src: "/root/uwsgi_exporter/uwsgi_exporter"
   dest: "/usr/local/bin/uwsgi_exporter"
   mode: "0755"
   remote_src: yes
  when:
    - gitresult.changed
  notify:
    - "restart uwsgi_exporter"

- name: "Remove Go build dep if we installed it"
  pkgng:
    name: "go"
    state: "absent"
  when:
    - gitresult.changed
    - goresult.changed

- name: "Remove gmake build dep if we installed it"
  pkgng:
    name: "gmake"
    state: "absent"
  when:
    - gitresult.changed
    - gmakeresult.changed

- name: "Create supervisord.d config file to run uwsgi_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "uwsgi_exporter"
    supervisord_programs:
      - name: "uwsgi_exporter"
        comment: "run uwsgi_exporter"
        command: "/usr/local/bin/uwsgi_exporter --stats.uri=http://[::1]:1717"
        user: "nobody"
    supervisord_extra_programs: []

- name: "Create exporter_exporter.d config file for uwsgi_exporter"
  include_role:
    name: "freebsd_base"
    tasks_from: "exporter_exporter.d"
  vars:
    expexp_filename: "uwsgi_exporter.yml"
    expexp_program:
      method: "http"
      http:
        port: 9117
