---
- name: "Install blackbox_exporter"
  pkgng:
    name: "blackbox_exporter"
    state: "present"
  notify:
    - "restart blackbox_exporter"

- name: "Install blackbox_exporter configuration"
  template:
    src: "blackbox_exporter.yml.j2"
    dest: "/usr/local/etc/blackbox_exporter.yml"
    owner: "promexp"
    group: "promexp"
    mode: "0644"
  notify:
    - "reload blackbox_exporter"

- name: "Create supervisord.d config file to run blackbox_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "blackbox_exporter"
    supervisord_programs:
      - name: "blackbox_exporter"
        comment: "run blackbox_exporter"
        command: "/usr/local/bin/blackbox_exporter --config.file=/usr/local/etc/blackbox_exporter.yml --web.listen-address={{ blackbox_exporter_listen_address }} --log.level={{ blackbox_exporter_log_level }}"
        user: "{{ blackbox_exporter_user }}"

- name: "Create exporter_exporter.d config file for blackbox_exporter"
  include_role:
    name: "freebsd_base"
    tasks_from: "exporter_exporter.d"
  vars:
    expexp_filename: "blackbox_exporter.yml"
    expexp_program:
      method: "http"
      http:
        port: 9115
        path: "/probe"
